name: Task 6 - Insecure Storage

on:
  push:
    paths:
      - '**.js'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install semgrep
      - run: semgrep --config semgrep/task6.yaml --error