name: Task X - Description

on:
  push:
    paths:
      - '**.js'

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config semgrep/taskX.yaml --error